name: SBOM with Snyk

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  snyk-sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Install Snyk CLI
        run: |
          curl -sL https://snyk.io/install.sh | bash
          snyk --version

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Generate SBOM (CycloneDX JSON)
        run: |
          snyk sbom --format=cyclonedx1.4+json --org=my-org --file=pom.xml > sbom-cyclonedx.json

      - name: Generate SBOM (SPDX JSON)
        run: |
          snyk sbom --format=spdx2.3+json --org=my-org --file=pom.xml > sbom-spdx.json

      - name: Upload SBOM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: snyk-sbom
          path: |
            sbom-cyclonedx.json
            sbom-spdx.json
